base_image:
    image: bolabaseten/comfyui-truss-base:6a7bc35
    python_executable_path: /usr/bin/python3
description: Deploy a ComfyUI workflow as a Truss
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: ComfyUI Workflow
secrets:
    hf_access_token: null
model_cache:
    - repo_id: stabilityai/stable-diffusion-3-medium
      allow_patterns:
          - sd3_medium_incl_clips.safetensors
          - clip_g.safetensors
          - clip_l.safetensors
python_version: py39
requirements:
    - websocket-client==1.6.4
    - accelerate==0.23.0
    - safetensors==0.4.3
    - torch==2.0.1
    - transformers==4.30.2
    - opencv-python
resources:
    accelerator: A10G
    use_gpu: true
system_packages:
    - wget
    - ffmpeg
    - libgl1-mesa-glx
