name: Run Local Shell Command

on:
  push:
    branches:
      - ai-model-deploy
  pull_request:
    branches:
      - ai-model-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESSES_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESSES_KEY }}
          aws-region: us-east-1 # Specify your AWS region
    - name: Run shell command
      run: |
        echo "Running local shell commands..."
        cd ./model_AI/SageMaker
        sh ./deploy_modelSagemaker.sh
        echo "starting to clearup the zip file..."
        rm -rf model-artifact/* && rm -rf model-artifact.tgz
