name: Media-Automation

# This workflow is triggered on pushes and pull requests to the main branch.
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npx eslint .
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }} # Match the version used in your Lambda
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Package Application
              run: zip -r archive.zip ./* -x "archive.zip" "./zip_files.sh" "./README.md" "./.*"

            - name: Deploy to AWS Lambda
              run:
                  aws lambda update-function-code --function-name automation-media \
                  --timeout 20 \
                  --zip-file fileb://archive.zip
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESSES_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESSES_KEY }}
                  AWS_REGION: us-east-1
