name: serverless-automation
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js 18 Release x86_64 Linux distributions
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
