name: Media-Automation

# This workflow is triggered on pushes and pull requests to the main branch.
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npx eslint .
            - name: Minify JavaScript files
              run: npx terser ./**/*.js --compress --mangle --output dist/

    deploy-aws:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Package Application
              run: zip -r archive.zip ./dist/* -x "archive.zip" "./zip_files.sh" "./README.md" "./.*"
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: nodejs-package
                  path: archive.zip
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: nodejs-package
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESSES_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESSES_KEY }}
                  aws-region: us-east-1 # Specify your AWS region
            - name: Update Lambda function code
              run: |
                  aws lambda update-function-code --function-name automation-media --zip-file fileb://archive.zip
            - name: Clean up
              run: rm -rf archive.zip
            - name: Deployed successfully
              run: echo "Deployed successfully"
